nodeLinker: pnp
enableGlobalCache: false

checksumBehavior: throw

supportedArchitectures:
  os:
    - current
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
